var encounter_info = '{"Version":1,'
	+ '"101":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"102":{"title":"kugong", "level":2, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"103":{"title":"kugong", "level":3, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"104":{"title":"kugong", "level":4, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"201":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"202":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"203":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"204":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"301":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"302":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"303":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"304":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"401":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"402":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"403":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"404":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"501":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"502":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"503":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"504":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"601":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"602":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"603":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"604":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"}}'
GameUI.EncounterInfo = JSON.parse(encounter_info)
$.Msg('load config encounter')