var encounter_info = '{"Version":1,'
	+ '"101":{"title":"kugong1", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"102":{"title":"kugong", "level":2, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"103":{"title":"kugong", "level":3, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"104":{"title":"kugong", "level":4, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"201":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"202":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"203":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"204":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"301":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"302":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"303":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"304":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"401":{"title":"芒果", "level":1, "story_desp":"他们穿过长夜而来，风尘仆仆，沉默寡言，眼中只有远方。“面包和水，换我主的恩泽。”人群中走出一人来，冲你低哑地说道。与他对视时，你真希望自己没看到对方兜帽下的样貌。不过这不失为一桩好买卖。", "effect_desp":"（获得一个恢复两点魔法值的芒果）"},'
	+ '"402":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"403":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"404":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"501":{"title":"shop1", "level":1, "story_desp":"shop laixi", "effect_desp":"jidi huixue"},'
	+ '"502":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"503":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"504":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"601":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"602":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"603":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"},'
	+ '"604":{"title":"kugong", "level":1, "story_desp":"kugong laixi", "effect_desp":"jidi huixue"}}'
GameUI.EncounterInfo = JSON.parse(encounter_info)
$.Msg('load config encounter')